#!/usr/bin/python

print "Content-Type: text/html\n"
print ""

import Imagga
import urllib2
import base64
import json
from pprint import pprint

user = input('Enter your URL: ')
#print str(user)
res = ''
color = ''
# generated by http://restunited.com
# for any feedback/issue with the code, please contact support{at}restunited.com

# initialize the API client
api_client = Imagga.swagger.ApiClient(api_server="https://api.imagga.com/v1")
# authentication setting using user name and password
api_client.username = 'acc_8a6c3db9bf7bbed'
api_client.password = 'dcee25efffb7d36584f06720ec661c1e'

try:
    tagging_api = Imagga.TaggingApi(api_client)
    # return TaggingResponse (model)
    response = tagging_api.tagging(url=str(user), content="sample_content")    
    res = (response)
    #pprint (res)

except urllib2.HTTPError, e:
    print('[HTTP Error {}]: {}'.format(e.code, e.reason))
    print('Request URL: {}'.format(e.geturl()))
    print('Response body: {}'.format(e.read()))
except urllib2.URLError, e:
    print('[URL Error]: {}'.format(e.reason))
except Exception, e:
    print(e)

try:
    colors_api = Imagga.ColorsApi(api_client)
    # return ColorsResponse (model)
    response = colors_api.extract_colors(url=str(user), content="sample_content", extract_overall_colors="1", extract_object_colors="1")    
    color = (response)
    #pprint (color)
except urllib2.HTTPError, e:
    print('[HTTP Error {}]: {}'.format(e.code, e.reason))
    print('Request URL: {}'.format(e.geturl()))
    print('Response body: {}'.format(e.read()))
except urllib2.URLError, e:
    print('[URL Error]: {}'.format(e.reason))
except Exception, e:
    print(e)

print res #tags
print color #colors

##f = open('no-sidebar.html', 'r')
##text = f.read()
##f.close()
##
##def filtr (text, str):
##    ace = str(text).find(str)
##    return ace
###print text
###before = text[:filtr(text)]
###text += '<div id="store">'
###text += str(res)
###text += '</div>'
###text += '<div id="store2">'
###text += str(color)
###text += '</div>'
##closing = '''
##    </body>
##    <script>
##        function enterURL() {
##            var un = prompt("Please enter a URL");
##        }
##    </script>
##</html>'''
##text += closing
##f = open('no-sidebar.html', 'w')
##new = f.write(text)
##f.close()
##
##f = open('no-sidebar.html', 'r')
##read = f.read()
##f.close()


final= str(color)
pos = final.find("'closest_palette_color_html_code'")
pos += len("'closest_palette_color_html_code'") + 3

finco = final[pos: (pos+ 7)]

def call():
    return '<html><body style="color:"'+str(finco)+'";"'+'<p>THIS IS YOUR SKIN COLOR:' + str(finco)+ ' YOUR SKIN COLOR IS THE BACKGROUND!</p></body></html>'
print read
print call()



